name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every 1 hours
    - cron: "*/60 * * * *"
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Profile Stats Image Generate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GitHub Full Year Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.STATS_GENERATE_TOKEN }}

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_rss: yes
          plugin_rss_source: https://cippands.wixsite.com/iotinj09/blog-feed.xml
          plugin_rss_limit: 5
