name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every 1 hours
    - cron: "*/60 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Profile Stats Image Generate

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GitHub Full Year Calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.STATS_GENERATE_TOKEN }}

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_rss: yes
          plugin_rss_source: https://cippands.wixsite.com/iotinj09/blog-feed.xml
          plugin_rss_limit: 5
          
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_API_TOKEN }}
          plugin_tweets_attachments: yes
          plugin_tweets_user: iotinJ09
          plugin_tweets_limit: 3
