name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every 1 hours
    - cron: "*/60 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Profile Summary Cards Generate

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Metrics Generate
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.STATS_GENERATE_TOKEN }}
