name: GitHub-Profile-Stats-Generate

on:
  schedule: # execute every 1 hours
    - cron: "*/60 * * * *"
  workflow_dispatch:

jobs:
  stats-generate:
    name: Profile Summary Cards Generate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.STATS_GENERATE_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.STATS_GENERATE_TOKEN }}
