name: GitHub-Profile-Summary-Cards-Build

on:
  schedule: # execute every 1 hours
    - cron: "*/60 * * * *"
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Profile Stats Image Generate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GitHub Stas Image Generate
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.STATS_GENERATE_TOKEN }}

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_rss: yes
          plugin_rss_source: https://cippands.wixsite.com/iotinj09/blog-feed.xml
          plugin_rss_limit: 5

  upload:
    name: Upload to Google Drive
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Upload to Google Drive

        uses: satackey/action-google-drive@v1

        with:
          skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
          upload-from: ./
          upload-to: ./共有フォルダ/GithubReadME

          # For those who set up Google Drive API client ID and secret themselves
          google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
