name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every 1 hours
    - cron: "*/60 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Profile Summary Cards Generate

    steps:
      - name: Summary Cards
        uses: actions/checkout@v2

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.STATS_GENERATE_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}

      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.STATS_GENERATE_TOKEN }}
